### PR TITLE
Remove Gemfile.lock from the repo.

### PR DESCRIPTION
**Pull request by gaffneyc**
It is general practice not to include Gemfile.lock in librararies[1]
since it "enforces precision that does not exist in the gem command".

1: http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

### CODE REVIEW

**Comment by kjohnston** [comment]
@gaffneyc, I remember going back and forth on this in some other projects, but will take a fresh look and followup in a few days.  Are you seeing any specific issues in your uses?

**Comment by gaffneyc** [comment]
I'm not seeing a specific issue, it's more a best practice guideline we've been following for years. From the post, applications care about the lock but libraries don't since `Gemfile.lock` is not used by anyone bringing the library into their application.

**Comment by kjohnston** [comment]
@gaffneyc, I'm good with this, and #43 as well, but they can't auto-merge at the moment.  If you could just submit one new PR containing both changes I'll merge that instead of these two.

**Comment by gaffneyc** [comment]
Sure thing, I will get that in the next day or two.

**Comment by gaffneyc** [comment]
Closing in favor of #44

**Pull request closed without merging**
